#!/bin/bash

echo "=== DNS 缓存清理指南 ==="
echo ""
echo "请按顺序执行以下操作："
echo ""
echo "1. 清除浏览器 DNS 缓存："
echo "   Mac: sudo dscacheutil -flushcache"
echo "   Windows: ipconfig /flushdns"
echo "   Linux: sudo systemctl restart systemd-resolved"
echo ""
echo "2. 清除 GitHub Pages 缓存："
echo "   - 在 https://github.com/Tswatery/tswatery.github.io/settings/pages"
echo "   - 反复点击 'Save' 按钮多次（强制刷新）"
echo ""
echo "3. 等待 10-15 分钟让 DNS 传播完成"
echo ""
echo "4. 验证 DNS 解析："
echo "   dig tswatery.github.io"
echo ""
echo "5. 如果您的域名提供商 (blog.xfl825.top) 设置了 CNAME："
echo "   - 删除所有指向 tswatery.github.io 的 CNAME 记录"
echo "   - 删除所有 A 记录"
echo "   - 清除域名提供商的缓存"
echo ""
echo "6. 重新触发部署："
echo "   git commit --allow-empty -m 'chore: force redeploy after DNS cleanup'"
echo "   git push origin main"
